### ISSUE TITLE
Exclude specific links

### ISSUE THREAD

**Issue by NicolaDau** [samwarnick/obsidian-simple-embeds#1]
It would be great to be able to easily exclude specific links from having an embed with a specific markdown syntax

**Comment by samwarnick** [comment]
I'll look into this more and try to figure out the best way to handle it, but my initial thought is to something like:

```
[Twitter link](https://twitter.com/johnvoorhees/status/1437735225086316548?s=21){embed=false}
```

But I don't love this because `{embed=false}` would show up in the preview if you disable this plugin. And perhaps a flag in the front matter as well to disable replacements for a whole file.

@NicolaDau are you aware of any other plugins that have a feature like this? I'd love to see how others are doing it before I reinvent the wheel. If not, I'll explore the API some more and see if I can find any other plugins doing something similar.

**Comment by steven-kraft** [comment]
Maybe you could use Obsidian's comment feature? For example:

`[Twitter link](https://twitter.com/johnvoorhees/status/1437735225086316548?s=21)%%noembed%%`

**Comment by samwarnick** [comment]
@steven-kraft Unfortunately, it appears that comments are removed from the HTML by the time I have access to replace the links, so I wouldn’t know if it’s been added or not. But a comment would be ideal, so I’ll keep looking to see if there’s a way to use it.

**Comment by NomarCub** [comment]
I think the most convenient and logical solution would be the default embed syntax (`!`) (which in Obsidian is itself an extension of the markdown spec's logic).
You'd use `![title](link)` when you want to embed something and `[title](link)` when you don't.
I hope this is implementable.

**Comment by samwarnick** [comment]
@NomarCub I see what you're saying, and that does look logical and simple. But since `![title](link)` is already a link to an image, I don't love the idea of putting a link to a website as an image—which would not work as expected if you open the file in another Markdown editor. But I will give this some more thought.

One of my (unstated) goals for making this plugin is progressive enhancement. Meaning, if it's at all possible, if you uninstall this plugin, you just get links as you'd expect, without any extra, bespoke syntax hanging around. With that in mind, I think I can at least implement a way to disable this plugin for a particular file using the front matter.

I did post in the forums about this. This feature seems like something that could/should be available to all users to disable plugins per file or markdown block. No responses yet, so I'll try again soon if there's still no response.

**Comment by samwarnick** [comment]
@NicolaDau would disabling for a file be enough, or are you really wanting to have a mix of several Twitter links in a single file, some shown as embeds, and some shown as links?

**Comment by nkoder** [comment]
Want to add my 2 cents: sometimes I have multiple links to tweets in a single file and I want to embed only the one I consider the main one. For now I do it as screenshots and maybe I will keep it that way as screenshots are not prone to tweet or account deletion. Or, I have a note with both Twitter and YouTube link and I only want single YouTube link to embed, while I prefer other to occupy minimal required space.

For me it to use this plugin it would be needed to:
- have control over individual links
- to have it opt-out by default (so I rather have to specify which link to embed rather to exclude every possible one)

But, to be clear, I probably can live good without this plugin, as I manage to achieve my needs with:
- screenshots and
- manually generated embeds with use of https://github.com/FHachez/obsidian-convert-url-to-iframe

So please do **not** consider my opinion important 😅

**Comment by NomarCub** [comment]
@samwarnick 
The `!` syntax is not invisible in other editors, but I think it's still pretty good for the goal you laid out in your 2nd paragraph.
Obsidian already uses it in ways that are not strictly compatible with other markdown, so this is not a new problem to be introduced to one's Obsidian notes. As far as I've seen, people in the community do use it for note, block, heading, etc. embeds.

I also come from a similar place to nkoder here. I have existing notes with links, and would want embedding to be opt-out by default and individually configurable. The `!` syntax suits these goals. The same as nkoder, I'm fine if this is not a popular idea or you personally don't want it.

**Comment by gerbsen** [comment]
I would like to see this feature too. I want to use a youtube video as a source. Now I have to see the youtube video and not my text.

What about this syntax.
`[Twitter link](!https://twitter.com/johnvoorhees/status/1437735225086316548?s=21)%%noembed%%`

or disabling it with whan there is a label specified. 

`[Twitter link|This is a label](https://twitter.com/johnvoorhees/status/1437735225086316548?s=21)`

**Comment by samwarnick** [comment]
Thanks @nkoder and @NomarCub for your input. Really helpful to understand other people's workflows. While I don't have those exact needs currently, I can see how I might want to do similar things in the future.

This is what I think I'm going to do:

1. Keep things simple out of the box. By default all matching links will be replaced with embeds.
2. Add a setting that puts the embed above the link, rather than replacing it. (Something I meant to add in the initial release, but forgot.)
3. Add ability to disable embeds using the format suggested by @gerbsen 
	- `[Descriptive text|noembed](https://twitter.com/user/status/123)`<sup>1</sup>
	- I like this the most so far because it is similar to the [syntax used to resize images](https://help.obsidian.md/How+to/Format+your+notes#Resizing+images) and it feels the least annoying to me personally if I were to disable or uninstall the plugin.
4. Add a setting to opt in to opting in 😄
	- With this enabled, no links would be replaced by default. They would have to be enabled like `[Descriptive text|embed](https://twitter.com/user/status/123)`<sup>1</sup>.

I like this because by default, everything remains vanilla markdown, and remains portable—which is important to me—and all complexity is opt in.

1: The `|noembed` and `|embed` would be removed from the text of the link in the preview so you wouldn't see it if the option to keep the link is enabled.

**Comment by nkoder** [comment]
(appendix to my previous post, only to clarify my wrong usage of a phrase: I probably should have written "opt-in" instead of "opt-out". What I meant is the case where I don't have something enabled by default)

**Comment by nkoder** [comment]
> Add a setting that puts the embed above the link, rather than replacing it. (Something I meant to add in the initial release, but forgot.)

love it! ❤️ 

> it is similar to the syntax used to resize images

sounds good and also I am using resize image syntax a lot too

the only doubt I have is how would it look with plugin *disabled* and whether it's a big issue or minor one: I just tried with something like `[tweet|noembed](https://twitter.com/nkoder/status/1442995743938256896)` and got `tweet|noembed` as a label. For me it is acceptable, especially if I opt-in for opt-in approach with `|embed`.

> Add a setting to opt in to opting in 😄

kind of a global setting which turn everything around, right? Sounds… clever 😄 Probably this is the one I would use in my case

**Comment by samwarnick** [comment]
> kind of a global setting which turn everything around, right? Sounds… clever 😄

Yup, global setting to turn everything around is right. Maybe a little too clever, but I figure some people would rather opt out and some would rather opt in, so why not make things ~~harder for myself~~ more flexible and support both modes.

**Comment by samwarnick** [comment]
Now supported in [v1.1.0](https://github.com/samwarnick/obsidian-simple-embeds/releases/tag/1.1.0)
