### ISSUE TITLE
Make it work with the live preview

### ISSUE THREAD

**Issue by moscowtimeNgD** [samwarnick/obsidian-simple-embeds#17]
Would be possible to make work with the new Live Preview?

**Comment by samwarnick** [comment]
Short answer: I'm not sure yet.

Longer answer: I haven't had time yet to look into this fully. When they first announced live preview, I believe they mentioned they would be adding an API that would make plugins like this one work, but I may have misunderstood since I haven't seen any more news about that. So I need to look into the existing APIs and see if I can make it work.

**Comment by NomarCub** [comment]
It'd be really convenient if it worked. I found this [how-to](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/How+to+update+your+plugins+and+CSS+for+live+preview) with some useful info. I know other plugins with content generated from code blocks that work, don't know about this kind.

**Comment by OnkelTem** [comment]
Hi folks.

I was looking for a way to preview YT videos not even leaving Obsidian, and some folks from the Obsidian Discord channel have kindly recommended me checkout this plugin. I found it great!

Now on to **Live Preview** mode. I think it's the best which has ever happened to Obsidian.
I didn't use Read Mode even when there was no Preview mode, let alone now, when Live Preview is here.

But Live Preview is not perfect.
For example, I don't like the current behavior of images, because they frantically popup in your editor not paying attention to how screwed your editor becomes after that.

Currently this plugin works exactly how it was designed. It doesn't produce any issues with Live Preview mode. 
And speaking of providing Live Preview support — it's not something what everybody would agree to have the same way (embedded content popping up automatically — is not the best idea).

There should be a trade-off, and I can propose the one which is on the surface as it's used quite often.

Here's a few screenshots from a Russian digg.com-clone. Initially YT links look almost like regular links, with the exception of little icon rendered right after the links:

![image](https://user-images.githubusercontent.com/114060/151614582-d605c458-ad8e-4a8a-8691-43a484df4002.png)

When you click this icon, it drops-down the iframe with the video of reasonable width:

![image](https://user-images.githubusercontent.com/114060/151616491-932dca85-5447-4d30-9fc1-6b30a32300d0.png)

Now you can watch it not leaving the discussion and not loosing context.

So that's my proposition: make it state-less and interactive in Live Preview mode.

**Comment by samwarnick** [comment]
@OnkelTem thanks for pointing this out and for the suggested implementation. I think that's a great idea. Some embeds, like GitHub gists, can be very long, which I'm sure would cause a poor editing experience if they were to just pop into existence like you said.

**Comment by qt-dork** [comment]
I'd rather it work the same as images instead, as the main things I plan on embedding would be tweets and youtube videos, and I'd rather them just show up by default.

**Comment by samwarnick** [comment]
Knowing me, there will most likely be a configuration to allow you to choose which behavior you'd like

**Comment by OnkelTem** [comment]
> I'd rather it work the same as images instead

Sure. That's why I said: _it's not something what everybody would agree to have the same way_ :)

So yeah, having it configurable would be the best option.

**Comment by OnkelTem** [comment]
I'm curious, does standard liik:

<pre>
[TITLE](LINK)
</pre>

support options? E.g.

<pre>
[TITLE | titleOptions](LINK | linkOptions)
</pre>

**Comment by NomarCub** [comment]
You might want to take a look at how [Ozan's Image in Editor Plugin](https://github.com/ozntel/oz-image-in-editor-obsidian) uses it.

**Comment by samwarnick** [comment]
> You might want to take a look at how [Ozan's Image in Editor Plugin](https://github.com/ozntel/oz-image-in-editor-obsidian) does iframes in live preview.

Need to dig through this some more, but this looks excellent. Thanks for finding and sharing @NomarCub

**Comment by samwarnick** [comment]
> I'm curious, does standard liik:
> 
> [TITLE](LINK)
> support options? E.g.
> 
> [TITLE | titleOptions](LINK | linkOptions)
> Can we use it somehow?

Links don't support options but default, but I have added some custom supported options using this syntax already—`|noemebd` and `|fullwidth`. So definitely can be used in this feature somehow.

**Comment by josephwper** [comment]
I would kill to have this working in Live Preview. This is the one of my biggest hangups right now with Obsidian is that I can't view Twitter and YouTube in Live Preview yet.

**Comment by Obadiahcruz** [comment]
+1 for this feature, hopefully you find a way to have it for live preview, im sure many would love it

**Comment by samwarnick** [comment]
Hey everyone, I've been working on this on and off the last few weeks, and I think I have things mostly working. Will release today in version 1.10.0. CodeMirror—which live preview uses—is very new to me, so I'm sure there will be bugs and edge cases I've missed. Feel free to create new issues as you come across them. PRs are also welcome 😄

For now, there is not an option for the collapsable embeds discussed above. Like I said, I'm very new to CodeMirror and was having quite a bit of trouble making it work the way I wanted. I've made #30 to hopefully add this in the future. But, live preview support is optional and can be disabled in the settings if you find it too obnoxious.

Thank you all for your interest in this plugin!
