### ISSUE TITLE
[Feature request] Markdown format for embedding

### ISSUE THREAD

**Issue by ehatle** [samwarnick/obsidian-simple-embeds#42]
`![[` is the standard format in Obsidian for embedding files and notes. I think it makes more sens to reuse this syntax instead of embedding every YouTube video into the notes and specifying which ones should be excluded with a `[[link|noembed]]`  parameter.

**Comment by samwarnick** [comment]
Thanks for the suggestion. I intentionally did not do this because I wanted maximum portability for my notes. To me, this plugin is just a progressive enhancement on top of regular links. There is a setting to opt out of replacing every link automatically if you do not like that behavior.

So for now, I'm not going to do this, but I will consider again if I do a 2.0 release. And anyone is welcome to fork this plugin and make a version that supports the file embed syntax.
